[package]
name = "hello_cargo"
version = "0.1.0"
authors = ["Webb Hinton <wyhinton@ncsu.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
specs = {version = "0.17.0", features = ["specs-derive"]}